export const GEAR_ACTIONS = {
  DELETE_ITEM: 'DELETE_ITEM',
  FETCH_TRIP_GEAR: 'FETCH_TRIP_GEAR',
  // REQUEST_USER_CLAIM_GEAR: 'REQUEST_USER_CLAI_GEAR',
  REQUEST_TRIP_GEAR: 'REQUEST_USER_TRIPS',
  SET_TRIP_GEAR: 'SET_TRIP_GEAR',
  CREATE_NEW_GEAR_ITEM: 'CREATE_NEW_GEAR_ITEM',
  REMOVE_ITEM_PROVIDER: 'REMOVE_ITEM_PROVIDER',
  UPDATE_ITEM_PROVIDER: 'UPDATE_ITEM_PROVIDER',
};
