export const TRIP_ACTIONS = {
    CREATE_NEW_TRIP: 'CREATE_NEW_TRIP',
    FETCH_USER_TRIPS: 'FETCH_USER_TRIPS',
    INVITE_USER: 'INVITE_USER',
    POST_CURRENT_TRIP: 'POST_CURRENT_TRIP',
    REQUEST_USER_JOIN_TRIP: 'REQUEST_USER_JOIN_TRIP',
    REQUEST_USER_LEAVE_TRIP: 'REQUEST_USER_LEAVE_TRIP',
    REQUEST_USER_TRIPS: 'REQUEST_USER_TRIPS',
    SET_CURRENT_TRIP: 'SET_CURRENT_TRIP',
    SET_CURRENT_TRIP_START: 'SET_CURRENT_TRIP_START',
    SET_CURRENT_TRIP_DONE: 'SET_CURRENT_TRIP_DONE',
    START_SAGA_SET_CURRENT_TRIP: 'START_SAGA_SET_CURRENT_TRIP',
    START_SAGA_SET_TRIP_CAMPER_LIST: 'START_SAGA_SET_TRIP_CAMPER_LIST',
    START_UNSET_CURRENT_TRIP: 'START_UNSET_CURRENT_TRIP',
    SET_CURRENT_TRIP_CAMPER_LIST: 'SET_CURRENT_TRIP_CAMPER_LIST',
    SET_USER_TRIPS: 'SET_USER_TRIPS',
    UNSET_CURRENT_TRIP: 'UNSET_CURRENT_TRIP'
  };
  