export const TRIP_ACTIONS = {
    FETCH_USER_TRIPS: 'FETCH_USER_TRIPS',
    REQUEST_USER_JOIN_TRIP: 'REQUEST_USER_JOIN_TRIP',
    REQUEST_USER_TRIPS: 'REQUEST_USER_TRIPS',
    SET_USER_TRIPS: 'SET_USER_TRIPS',
  };
  